#!/usr/bin/env bash
#  The redirection must be a “301 Moved Permanently”
#  You answer file should be a Bash script containing commands to 
#  automatically configure a Ubuntu machine to respect above requirements
#  Using what you did with 1-install_nginx_web_server, 
#  write 3-redirection so that it configures a brand new Ubuntu machine 
#  to the requirements asked in this task
sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://twitter.com/home;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
