#!/usr/bin/env bash
#  Configure your Nginx server to have a custom 404 page that contains 
#  the string Ceci n'est pas une page.
#  Requirements:
#  The page must return an HTTP 404 error code
#  The page must contain the string Ceci n'est pas une page
#  Using what you did with 3-redirection, write 4-not_found_page_404 
#  so that it configures a brand new Ubuntu machine to the requirements 
#  asked in this task
apt-get update
apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.linkedin.com/in/elvis-oguoma;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
