#!/usr/bin/env bash
#  Configure your Nginx server to have a custom 404 page that contains 
#  the string Ceci n'est pas une page.
#  Requirements:
#  The page must return an HTTP 404 error code
#  The page must contain the string Ceci n'est pas une page
#  Using what you did with 3-redirection, write 4-not_found_page_404 
#  so that it configures a brand new Ubuntu machine to the requirements 
#  asked in this task
sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.linkedin.com/in/elvis-oguoma;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx reload
